# Generated by Django 3.2.6 on 2021-08-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='автор')),
                ('content', models.TextField(blank=True, verbose_name='коментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата публкации')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blok.sportnews')),
            ],
        ),
    ]
