# Generated by Django 3.2.6 on 2021-08-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blok', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comments',
        ),
    ]
